# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: xlabsf.github.io
title: Xlab
email: xlab.contact@gmail.com
author: Xlab
description: > # "A tech + design company
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2019 Xlab . All Rights Reserved.'
credits: 'Credits <a href="http://startbootstrap.com/">Start Bootstrap </a> and <a href="http://freepik.com"> Freepik </a>'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/xlabsf
  - title: facebook
    url: https://www.facebook.com/Xlab-2365741440349177/
  - title: medium
    url: https://medium.com/@xlab.contact
